url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team
people:
- name: Gino K.
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/TheRealBitbill

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Riverside, CA 92503

# Build settings
markdown: kramdown
permalink: pretty
